image:
- Visual Studio 2022
#- macOS
#- Ubuntu

skip_branch_with_pr: true
stack: python 3.12

environment:
  GITHUB_TOKEN:
    secure: BBpVQhKwPvOdELLahF5Z9pOJbZPaW5DU1TE14qf9QOtZYZEMl+NV5IKfiNgYCvWh

install:
- pip install -r requirements.txt
- py -m pip install --upgrade pip
- py -m pip install pyinstaller

before_build:
#- cmd:  |
# C:\Python312\python.exe -m pip install --upgrade pip
# C:\Python312\python.exe -m pip install --upgrade pip
#- pwsh:
#    pip install --upgrade pip
#    pip install pyinstaller
#- ps: |
#  C:\Python312\python.exe -m pip install pyinstaller
#  C:\Python312\python.exe -m pip install --upgrade pip

build_script:
#- flet pack main.py --name efforttrix --icon icon.png --product-name efforttrix --product-version "1.0.0" --copyright "Copyright (c) 2022 YourCompany Inc."
- flet pack main.py --name efforttrix --product-name efforttrix --product-version "0.1" --copyright "Copyright (c) 2024 CLXS BDM Team."

test: off

# Publish artifacts to GitHub Releases on "tag" builds
deploy:
  provider: GitHub
  auth_token: $(GITHUB_TOKEN)
  on:
    appveyor_repo_tag: true

#
#   Windows package
# 
for:
-
  matrix:
    only:
    - image: Visual Studio 2019

  after_build:
  - 7z a efforttrix-windows.zip %CD%\dist\*.exe

  artifacts:
  - path: efforttrix-windows.zip

#
#   macOS package
# 
-
  matrix:
    only:
    - image: macOS

  after_build:
  - tar -czvf efforttrix-macos.tar.gz -C dist efforttrix.app

  artifacts:
  - path: efforttrix-macos.tar.gz

#
#   Linux package
# 
-
  matrix:
    only:
    - image: Ubuntu

  after_build:
  - tar -czvf efforttrix-linux.tar.gz -C dist efforttrix

  artifacts:
  - path: efforttrix-linux.tar.gz
